### PR TITLE
WIP: support for DNF 3.0

### PR DESCRIPTION
**Pull request by edynox**
Dnf 2.8 introduces unified software database which changes some non-API
calls.

P.S. I have not tested it yet - it breaks unit tests.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@edynox Thanks for this! Could you please get it into mergeable shape?

**Comment by edynox** [comment]
@Conan-Kudo I have some trouble running unit tests (by `make run-tests-unit`).
I am getting:
```
======================================================================
ERROR: Test the backend packages
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dnfdaemon/test/test_common.py", line 155, in test_packages
    base = support.MockBase('main')
  File "/dnfdaemon/test/support.py", line 86, in __init__
    repo = MockRepo(r, None)
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 514, in __init__
    super(Repo, self).__init__(section=name, parent=parent_conf)
  File "/usr/lib/python3.6/site-packages/dnf/conf/config.py", line 959, in __init__
    self._add_option('enabled', inherit(parent._get_option('enabled')))
AttributeError: 'NoneType' object has no attribute '_get_option'
```
I tried to rewrite `test_support` to Swdb compatible form, but it has to be tested first (and probably changed in other tests as well)...

**Comment by Conan-Kudo** [comment]
@edynox Looks like DNF broke more APIs... :/

**Comment by dmach** [comment]
Can you close this PR?
I created PR#22 that fixes more issues.

**Comment by Conan-Kudo** [comment]
Sure.

**Pull request closed without merging**
